services:
  mdma-frontend:
    build: ./client-app
    ports:
      - "3000:3000"
    depends_on:
      - mdma-backend
    environment:
      - REACT_APP_BACKEND_API_BASE_URL=http://localhost:5000/

  mdma-backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mdma-database
    environment:
      - DATABASE_URL=postgresql://admin:admin@mdma-database:5432/mdma

  mdma-database:
    image: postgres
    container_name: mdma-database-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"


volumes:
  postgres-data:
